# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cps_enterprise_v4_pb2 as cps__enterprise__v4__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cps_enterprise_v4_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountingSwarmProtocolStub(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SECTION 9: ACCOUNTING SWARM PROTOCOL (gRPC Services)
    ═══════════════════════════════════════════════════════════════════════════════

    ─── Unary RPCs ───
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BroadcastFinancialEvent = channel.unary_unary(
                '/cps.enterprise.v4.AccountingSwarmProtocol/BroadcastFinancialEvent',
                request_serializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.AckResponse.FromString,
                _registered_method=True)
        self.GetEventById = channel.unary_unary(
                '/cps.enterprise.v4.AccountingSwarmProtocol/GetEventById',
                request_serializer=cps__enterprise__v4__pb2.GetEventRequest.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.FromString,
                _registered_method=True)
        self.GetEventsByRange = channel.unary_unary(
                '/cps.enterprise.v4.AccountingSwarmProtocol/GetEventsByRange',
                request_serializer=cps__enterprise__v4__pb2.GetEventsRangeRequest.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.EventBatch.FromString,
                _registered_method=True)
        self.RequestReconciliation = channel.unary_unary(
                '/cps.enterprise.v4.AccountingSwarmProtocol/RequestReconciliation',
                request_serializer=cps__enterprise__v4__pb2.ReconciliationRequest.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.ReconciliationResponse.FromString,
                _registered_method=True)
        self.ResolveLedgerConflict = channel.unary_unary(
                '/cps.enterprise.v4.AccountingSwarmProtocol/ResolveLedgerConflict',
                request_serializer=cps__enterprise__v4__pb2.ConflictResolutionRequest.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/cps.enterprise.v4.AccountingSwarmProtocol/SubscribeEvents',
                request_serializer=cps__enterprise__v4__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.FromString,
                _registered_method=True)
        self.StreamReconciliation = channel.unary_stream(
                '/cps.enterprise.v4.AccountingSwarmProtocol/StreamReconciliation',
                request_serializer=cps__enterprise__v4__pb2.ReconciliationRequest.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.ReconciliationResponse.FromString,
                _registered_method=True)
        self.StreamOfflineEvents = channel.stream_unary(
                '/cps.enterprise.v4.AccountingSwarmProtocol/StreamOfflineEvents',
                request_serializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.BatchAckResponse.FromString,
                _registered_method=True)
        self.StreamCRDTUpdates = channel.stream_unary(
                '/cps.enterprise.v4.AccountingSwarmProtocol/StreamCRDTUpdates',
                request_serializer=cps__enterprise__v4__pb2.CRDTStateBundle.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.BatchAckResponse.FromString,
                _registered_method=True)
        self.SwarmEventExchange = channel.stream_stream(
                '/cps.enterprise.v4.AccountingSwarmProtocol/SwarmEventExchange',
                request_serializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.FromString,
                _registered_method=True)
        self.SyncCRDTState = channel.stream_stream(
                '/cps.enterprise.v4.AccountingSwarmProtocol/SyncCRDTState',
                request_serializer=cps__enterprise__v4__pb2.CRDTStateBundle.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.CRDTStateBundle.FromString,
                _registered_method=True)
        self.AgentCommunication = channel.stream_stream(
                '/cps.enterprise.v4.AccountingSwarmProtocol/AgentCommunication',
                request_serializer=cps__enterprise__v4__pb2.AgentMessage.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.AgentMessage.FromString,
                _registered_method=True)


class AccountingSwarmProtocolServicer(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SECTION 9: ACCOUNTING SWARM PROTOCOL (gRPC Services)
    ═══════════════════════════════════════════════════════════════════════════════

    ─── Unary RPCs ───
    """

    def BroadcastFinancialEvent(self, request, context):
        """Broadcast single financial event
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventById(self, request, context):
        """Query event by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventsByRange(self, request, context):
        """Query events by range
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestReconciliation(self, request, context):
        """Request reconciliation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveLedgerConflict(self, request, context):
        """Resolve conflicts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """─── Server Streaming RPCs ───

        Subscribe to event stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamReconciliation(self, request, context):
        """Stream reconciliation results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOfflineEvents(self, request_iterator, context):
        """─── Client Streaming RPCs ───

        Stream offline events for batch sync
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCRDTUpdates(self, request_iterator, context):
        """Stream CRDT state updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwarmEventExchange(self, request_iterator, context):
        """─── Bidirectional Streaming RPCs ───

        Real-time swarm event exchange
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncCRDTState(self, request_iterator, context):
        """CRDT state synchronization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentCommunication(self, request_iterator, context):
        """Agent communication channel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountingSwarmProtocolServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BroadcastFinancialEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastFinancialEvent,
                    request_deserializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.FromString,
                    response_serializer=cps__enterprise__v4__pb2.AckResponse.SerializeToString,
            ),
            'GetEventById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventById,
                    request_deserializer=cps__enterprise__v4__pb2.GetEventRequest.FromString,
                    response_serializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.SerializeToString,
            ),
            'GetEventsByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventsByRange,
                    request_deserializer=cps__enterprise__v4__pb2.GetEventsRangeRequest.FromString,
                    response_serializer=cps__enterprise__v4__pb2.EventBatch.SerializeToString,
            ),
            'RequestReconciliation': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestReconciliation,
                    request_deserializer=cps__enterprise__v4__pb2.ReconciliationRequest.FromString,
                    response_serializer=cps__enterprise__v4__pb2.ReconciliationResponse.SerializeToString,
            ),
            'ResolveLedgerConflict': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveLedgerConflict,
                    request_deserializer=cps__enterprise__v4__pb2.ConflictResolutionRequest.FromString,
                    response_serializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=cps__enterprise__v4__pb2.SubscribeRequest.FromString,
                    response_serializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.SerializeToString,
            ),
            'StreamReconciliation': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamReconciliation,
                    request_deserializer=cps__enterprise__v4__pb2.ReconciliationRequest.FromString,
                    response_serializer=cps__enterprise__v4__pb2.ReconciliationResponse.SerializeToString,
            ),
            'StreamOfflineEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamOfflineEvents,
                    request_deserializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.FromString,
                    response_serializer=cps__enterprise__v4__pb2.BatchAckResponse.SerializeToString,
            ),
            'StreamCRDTUpdates': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamCRDTUpdates,
                    request_deserializer=cps__enterprise__v4__pb2.CRDTStateBundle.FromString,
                    response_serializer=cps__enterprise__v4__pb2.BatchAckResponse.SerializeToString,
            ),
            'SwarmEventExchange': grpc.stream_stream_rpc_method_handler(
                    servicer.SwarmEventExchange,
                    request_deserializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.FromString,
                    response_serializer=cps__enterprise__v4__pb2.SovereignFinancialEvent.SerializeToString,
            ),
            'SyncCRDTState': grpc.stream_stream_rpc_method_handler(
                    servicer.SyncCRDTState,
                    request_deserializer=cps__enterprise__v4__pb2.CRDTStateBundle.FromString,
                    response_serializer=cps__enterprise__v4__pb2.CRDTStateBundle.SerializeToString,
            ),
            'AgentCommunication': grpc.stream_stream_rpc_method_handler(
                    servicer.AgentCommunication,
                    request_deserializer=cps__enterprise__v4__pb2.AgentMessage.FromString,
                    response_serializer=cps__enterprise__v4__pb2.AgentMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cps.enterprise.v4.AccountingSwarmProtocol', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cps.enterprise.v4.AccountingSwarmProtocol', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountingSwarmProtocol(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SECTION 9: ACCOUNTING SWARM PROTOCOL (gRPC Services)
    ═══════════════════════════════════════════════════════════════════════════════

    ─── Unary RPCs ───
    """

    @staticmethod
    def BroadcastFinancialEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cps.enterprise.v4.AccountingSwarmProtocol/BroadcastFinancialEvent',
            cps__enterprise__v4__pb2.SovereignFinancialEvent.SerializeToString,
            cps__enterprise__v4__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cps.enterprise.v4.AccountingSwarmProtocol/GetEventById',
            cps__enterprise__v4__pb2.GetEventRequest.SerializeToString,
            cps__enterprise__v4__pb2.SovereignFinancialEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventsByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cps.enterprise.v4.AccountingSwarmProtocol/GetEventsByRange',
            cps__enterprise__v4__pb2.GetEventsRangeRequest.SerializeToString,
            cps__enterprise__v4__pb2.EventBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestReconciliation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cps.enterprise.v4.AccountingSwarmProtocol/RequestReconciliation',
            cps__enterprise__v4__pb2.ReconciliationRequest.SerializeToString,
            cps__enterprise__v4__pb2.ReconciliationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveLedgerConflict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cps.enterprise.v4.AccountingSwarmProtocol/ResolveLedgerConflict',
            cps__enterprise__v4__pb2.ConflictResolutionRequest.SerializeToString,
            cps__enterprise__v4__pb2.SovereignFinancialEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cps.enterprise.v4.AccountingSwarmProtocol/SubscribeEvents',
            cps__enterprise__v4__pb2.SubscribeRequest.SerializeToString,
            cps__enterprise__v4__pb2.SovereignFinancialEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamReconciliation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cps.enterprise.v4.AccountingSwarmProtocol/StreamReconciliation',
            cps__enterprise__v4__pb2.ReconciliationRequest.SerializeToString,
            cps__enterprise__v4__pb2.ReconciliationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOfflineEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/cps.enterprise.v4.AccountingSwarmProtocol/StreamOfflineEvents',
            cps__enterprise__v4__pb2.SovereignFinancialEvent.SerializeToString,
            cps__enterprise__v4__pb2.BatchAckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCRDTUpdates(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/cps.enterprise.v4.AccountingSwarmProtocol/StreamCRDTUpdates',
            cps__enterprise__v4__pb2.CRDTStateBundle.SerializeToString,
            cps__enterprise__v4__pb2.BatchAckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwarmEventExchange(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cps.enterprise.v4.AccountingSwarmProtocol/SwarmEventExchange',
            cps__enterprise__v4__pb2.SovereignFinancialEvent.SerializeToString,
            cps__enterprise__v4__pb2.SovereignFinancialEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncCRDTState(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cps.enterprise.v4.AccountingSwarmProtocol/SyncCRDTState',
            cps__enterprise__v4__pb2.CRDTStateBundle.SerializeToString,
            cps__enterprise__v4__pb2.CRDTStateBundle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentCommunication(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cps.enterprise.v4.AccountingSwarmProtocol/AgentCommunication',
            cps__enterprise__v4__pb2.AgentMessage.SerializeToString,
            cps__enterprise__v4__pb2.AgentMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class QueryProtocolStub(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SECTION 10: QUERY & PROJECTION PROTOCOL
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBranchSummary = channel.unary_unary(
                '/cps.enterprise.v4.QueryProtocol/GetBranchSummary',
                request_serializer=cps__enterprise__v4__pb2.BranchQuery.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.BranchSummary.FromString,
                _registered_method=True)
        self.GetInventoryStatus = channel.unary_unary(
                '/cps.enterprise.v4.QueryProtocol/GetInventoryStatus',
                request_serializer=cps__enterprise__v4__pb2.InventoryQuery.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.InventoryStatus.FromString,
                _registered_method=True)
        self.GetSalesReport = channel.unary_unary(
                '/cps.enterprise.v4.QueryProtocol/GetSalesReport',
                request_serializer=cps__enterprise__v4__pb2.SalesReportQuery.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.SalesReport.FromString,
                _registered_method=True)
        self.GetLedgerBalance = channel.unary_unary(
                '/cps.enterprise.v4.QueryProtocol/GetLedgerBalance',
                request_serializer=cps__enterprise__v4__pb2.LedgerQuery.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.LedgerBalance.FromString,
                _registered_method=True)
        self.SubscribeDashboard = channel.unary_stream(
                '/cps.enterprise.v4.QueryProtocol/SubscribeDashboard',
                request_serializer=cps__enterprise__v4__pb2.DashboardSubscription.SerializeToString,
                response_deserializer=cps__enterprise__v4__pb2.DashboardUpdate.FromString,
                _registered_method=True)


class QueryProtocolServicer(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SECTION 10: QUERY & PROJECTION PROTOCOL
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def GetBranchSummary(self, request, context):
        """Read model queries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInventoryStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSalesReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLedgerBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeDashboard(self, request, context):
        """Real-time projections
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryProtocolServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBranchSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBranchSummary,
                    request_deserializer=cps__enterprise__v4__pb2.BranchQuery.FromString,
                    response_serializer=cps__enterprise__v4__pb2.BranchSummary.SerializeToString,
            ),
            'GetInventoryStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInventoryStatus,
                    request_deserializer=cps__enterprise__v4__pb2.InventoryQuery.FromString,
                    response_serializer=cps__enterprise__v4__pb2.InventoryStatus.SerializeToString,
            ),
            'GetSalesReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesReport,
                    request_deserializer=cps__enterprise__v4__pb2.SalesReportQuery.FromString,
                    response_serializer=cps__enterprise__v4__pb2.SalesReport.SerializeToString,
            ),
            'GetLedgerBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLedgerBalance,
                    request_deserializer=cps__enterprise__v4__pb2.LedgerQuery.FromString,
                    response_serializer=cps__enterprise__v4__pb2.LedgerBalance.SerializeToString,
            ),
            'SubscribeDashboard': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeDashboard,
                    request_deserializer=cps__enterprise__v4__pb2.DashboardSubscription.FromString,
                    response_serializer=cps__enterprise__v4__pb2.DashboardUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cps.enterprise.v4.QueryProtocol', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cps.enterprise.v4.QueryProtocol', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryProtocol(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SECTION 10: QUERY & PROJECTION PROTOCOL
    ═══════════════════════════════════════════════════════════════════════════════

    """

    @staticmethod
    def GetBranchSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cps.enterprise.v4.QueryProtocol/GetBranchSummary',
            cps__enterprise__v4__pb2.BranchQuery.SerializeToString,
            cps__enterprise__v4__pb2.BranchSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInventoryStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cps.enterprise.v4.QueryProtocol/GetInventoryStatus',
            cps__enterprise__v4__pb2.InventoryQuery.SerializeToString,
            cps__enterprise__v4__pb2.InventoryStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSalesReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cps.enterprise.v4.QueryProtocol/GetSalesReport',
            cps__enterprise__v4__pb2.SalesReportQuery.SerializeToString,
            cps__enterprise__v4__pb2.SalesReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLedgerBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cps.enterprise.v4.QueryProtocol/GetLedgerBalance',
            cps__enterprise__v4__pb2.LedgerQuery.SerializeToString,
            cps__enterprise__v4__pb2.LedgerBalance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cps.enterprise.v4.QueryProtocol/SubscribeDashboard',
            cps__enterprise__v4__pb2.DashboardSubscription.SerializeToString,
            cps__enterprise__v4__pb2.DashboardUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
