// ═══════════════════════════════════════════════════════════════════════════════
// CP'S Enterprise Dynamics Commerce System (DCS) v4.0
// Protocol Buffers Schema - Sovereign Architecture
// ═══════════════════════════════════════════════════════════════════════════════
// Author: Ahmed Hajjaj - Full-Spectrum Architect
// License: Proprietary - Internal Use Only
// ═══════════════════════════════════════════════════════════════════════════════

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: cps_enterprise_v4.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountingSwarmProtocol_BroadcastFinancialEvent_FullMethodName = "/cps.enterprise.v4.AccountingSwarmProtocol/BroadcastFinancialEvent"
	AccountingSwarmProtocol_GetEventById_FullMethodName            = "/cps.enterprise.v4.AccountingSwarmProtocol/GetEventById"
	AccountingSwarmProtocol_GetEventsByRange_FullMethodName        = "/cps.enterprise.v4.AccountingSwarmProtocol/GetEventsByRange"
	AccountingSwarmProtocol_RequestReconciliation_FullMethodName   = "/cps.enterprise.v4.AccountingSwarmProtocol/RequestReconciliation"
	AccountingSwarmProtocol_ResolveLedgerConflict_FullMethodName   = "/cps.enterprise.v4.AccountingSwarmProtocol/ResolveLedgerConflict"
	AccountingSwarmProtocol_SubscribeEvents_FullMethodName         = "/cps.enterprise.v4.AccountingSwarmProtocol/SubscribeEvents"
	AccountingSwarmProtocol_StreamReconciliation_FullMethodName    = "/cps.enterprise.v4.AccountingSwarmProtocol/StreamReconciliation"
	AccountingSwarmProtocol_StreamOfflineEvents_FullMethodName     = "/cps.enterprise.v4.AccountingSwarmProtocol/StreamOfflineEvents"
	AccountingSwarmProtocol_StreamCRDTUpdates_FullMethodName       = "/cps.enterprise.v4.AccountingSwarmProtocol/StreamCRDTUpdates"
	AccountingSwarmProtocol_SwarmEventExchange_FullMethodName      = "/cps.enterprise.v4.AccountingSwarmProtocol/SwarmEventExchange"
	AccountingSwarmProtocol_SyncCRDTState_FullMethodName           = "/cps.enterprise.v4.AccountingSwarmProtocol/SyncCRDTState"
	AccountingSwarmProtocol_AgentCommunication_FullMethodName      = "/cps.enterprise.v4.AccountingSwarmProtocol/AgentCommunication"
)

// AccountingSwarmProtocolClient is the client API for AccountingSwarmProtocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountingSwarmProtocolClient interface {
	// Broadcast single financial event
	BroadcastFinancialEvent(ctx context.Context, in *SovereignFinancialEvent, opts ...grpc.CallOption) (*AckResponse, error)
	// Query event by ID
	GetEventById(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*SovereignFinancialEvent, error)
	// Query events by range
	GetEventsByRange(ctx context.Context, in *GetEventsRangeRequest, opts ...grpc.CallOption) (*EventBatch, error)
	// Request reconciliation
	RequestReconciliation(ctx context.Context, in *ReconciliationRequest, opts ...grpc.CallOption) (*ReconciliationResponse, error)
	// Resolve conflicts
	ResolveLedgerConflict(ctx context.Context, in *ConflictResolutionRequest, opts ...grpc.CallOption) (*SovereignFinancialEvent, error)
	// Subscribe to event stream
	SubscribeEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SovereignFinancialEvent], error)
	// Stream reconciliation results
	StreamReconciliation(ctx context.Context, in *ReconciliationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReconciliationResponse], error)
	// Stream offline events for batch sync
	StreamOfflineEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SovereignFinancialEvent, BatchAckResponse], error)
	// Stream CRDT state updates
	StreamCRDTUpdates(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CRDTStateBundle, BatchAckResponse], error)
	// Real-time swarm event exchange
	SwarmEventExchange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SovereignFinancialEvent, SovereignFinancialEvent], error)
	// CRDT state synchronization
	SyncCRDTState(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CRDTStateBundle, CRDTStateBundle], error)
	// Agent communication channel
	AgentCommunication(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, AgentMessage], error)
}

type accountingSwarmProtocolClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountingSwarmProtocolClient(cc grpc.ClientConnInterface) AccountingSwarmProtocolClient {
	return &accountingSwarmProtocolClient{cc}
}

func (c *accountingSwarmProtocolClient) BroadcastFinancialEvent(ctx context.Context, in *SovereignFinancialEvent, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, AccountingSwarmProtocol_BroadcastFinancialEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountingSwarmProtocolClient) GetEventById(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*SovereignFinancialEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SovereignFinancialEvent)
	err := c.cc.Invoke(ctx, AccountingSwarmProtocol_GetEventById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountingSwarmProtocolClient) GetEventsByRange(ctx context.Context, in *GetEventsRangeRequest, opts ...grpc.CallOption) (*EventBatch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventBatch)
	err := c.cc.Invoke(ctx, AccountingSwarmProtocol_GetEventsByRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountingSwarmProtocolClient) RequestReconciliation(ctx context.Context, in *ReconciliationRequest, opts ...grpc.CallOption) (*ReconciliationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconciliationResponse)
	err := c.cc.Invoke(ctx, AccountingSwarmProtocol_RequestReconciliation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountingSwarmProtocolClient) ResolveLedgerConflict(ctx context.Context, in *ConflictResolutionRequest, opts ...grpc.CallOption) (*SovereignFinancialEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SovereignFinancialEvent)
	err := c.cc.Invoke(ctx, AccountingSwarmProtocol_ResolveLedgerConflict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountingSwarmProtocolClient) SubscribeEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SovereignFinancialEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccountingSwarmProtocol_ServiceDesc.Streams[0], AccountingSwarmProtocol_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SovereignFinancialEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_SubscribeEventsClient = grpc.ServerStreamingClient[SovereignFinancialEvent]

func (c *accountingSwarmProtocolClient) StreamReconciliation(ctx context.Context, in *ReconciliationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReconciliationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccountingSwarmProtocol_ServiceDesc.Streams[1], AccountingSwarmProtocol_StreamReconciliation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReconciliationRequest, ReconciliationResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_StreamReconciliationClient = grpc.ServerStreamingClient[ReconciliationResponse]

func (c *accountingSwarmProtocolClient) StreamOfflineEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SovereignFinancialEvent, BatchAckResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccountingSwarmProtocol_ServiceDesc.Streams[2], AccountingSwarmProtocol_StreamOfflineEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SovereignFinancialEvent, BatchAckResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_StreamOfflineEventsClient = grpc.ClientStreamingClient[SovereignFinancialEvent, BatchAckResponse]

func (c *accountingSwarmProtocolClient) StreamCRDTUpdates(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CRDTStateBundle, BatchAckResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccountingSwarmProtocol_ServiceDesc.Streams[3], AccountingSwarmProtocol_StreamCRDTUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CRDTStateBundle, BatchAckResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_StreamCRDTUpdatesClient = grpc.ClientStreamingClient[CRDTStateBundle, BatchAckResponse]

func (c *accountingSwarmProtocolClient) SwarmEventExchange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SovereignFinancialEvent, SovereignFinancialEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccountingSwarmProtocol_ServiceDesc.Streams[4], AccountingSwarmProtocol_SwarmEventExchange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SovereignFinancialEvent, SovereignFinancialEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_SwarmEventExchangeClient = grpc.BidiStreamingClient[SovereignFinancialEvent, SovereignFinancialEvent]

func (c *accountingSwarmProtocolClient) SyncCRDTState(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CRDTStateBundle, CRDTStateBundle], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccountingSwarmProtocol_ServiceDesc.Streams[5], AccountingSwarmProtocol_SyncCRDTState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CRDTStateBundle, CRDTStateBundle]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_SyncCRDTStateClient = grpc.BidiStreamingClient[CRDTStateBundle, CRDTStateBundle]

func (c *accountingSwarmProtocolClient) AgentCommunication(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, AgentMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccountingSwarmProtocol_ServiceDesc.Streams[6], AccountingSwarmProtocol_AgentCommunication_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, AgentMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_AgentCommunicationClient = grpc.BidiStreamingClient[AgentMessage, AgentMessage]

// AccountingSwarmProtocolServer is the server API for AccountingSwarmProtocol service.
// All implementations must embed UnimplementedAccountingSwarmProtocolServer
// for forward compatibility.
type AccountingSwarmProtocolServer interface {
	// Broadcast single financial event
	BroadcastFinancialEvent(context.Context, *SovereignFinancialEvent) (*AckResponse, error)
	// Query event by ID
	GetEventById(context.Context, *GetEventRequest) (*SovereignFinancialEvent, error)
	// Query events by range
	GetEventsByRange(context.Context, *GetEventsRangeRequest) (*EventBatch, error)
	// Request reconciliation
	RequestReconciliation(context.Context, *ReconciliationRequest) (*ReconciliationResponse, error)
	// Resolve conflicts
	ResolveLedgerConflict(context.Context, *ConflictResolutionRequest) (*SovereignFinancialEvent, error)
	// Subscribe to event stream
	SubscribeEvents(*SubscribeRequest, grpc.ServerStreamingServer[SovereignFinancialEvent]) error
	// Stream reconciliation results
	StreamReconciliation(*ReconciliationRequest, grpc.ServerStreamingServer[ReconciliationResponse]) error
	// Stream offline events for batch sync
	StreamOfflineEvents(grpc.ClientStreamingServer[SovereignFinancialEvent, BatchAckResponse]) error
	// Stream CRDT state updates
	StreamCRDTUpdates(grpc.ClientStreamingServer[CRDTStateBundle, BatchAckResponse]) error
	// Real-time swarm event exchange
	SwarmEventExchange(grpc.BidiStreamingServer[SovereignFinancialEvent, SovereignFinancialEvent]) error
	// CRDT state synchronization
	SyncCRDTState(grpc.BidiStreamingServer[CRDTStateBundle, CRDTStateBundle]) error
	// Agent communication channel
	AgentCommunication(grpc.BidiStreamingServer[AgentMessage, AgentMessage]) error
	mustEmbedUnimplementedAccountingSwarmProtocolServer()
}

// UnimplementedAccountingSwarmProtocolServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountingSwarmProtocolServer struct{}

func (UnimplementedAccountingSwarmProtocolServer) BroadcastFinancialEvent(context.Context, *SovereignFinancialEvent) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadcastFinancialEvent not implemented")
}
func (UnimplementedAccountingSwarmProtocolServer) GetEventById(context.Context, *GetEventRequest) (*SovereignFinancialEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventById not implemented")
}
func (UnimplementedAccountingSwarmProtocolServer) GetEventsByRange(context.Context, *GetEventsRangeRequest) (*EventBatch, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsByRange not implemented")
}
func (UnimplementedAccountingSwarmProtocolServer) RequestReconciliation(context.Context, *ReconciliationRequest) (*ReconciliationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestReconciliation not implemented")
}
func (UnimplementedAccountingSwarmProtocolServer) ResolveLedgerConflict(context.Context, *ConflictResolutionRequest) (*SovereignFinancialEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveLedgerConflict not implemented")
}
func (UnimplementedAccountingSwarmProtocolServer) SubscribeEvents(*SubscribeRequest, grpc.ServerStreamingServer[SovereignFinancialEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedAccountingSwarmProtocolServer) StreamReconciliation(*ReconciliationRequest, grpc.ServerStreamingServer[ReconciliationResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamReconciliation not implemented")
}
func (UnimplementedAccountingSwarmProtocolServer) StreamOfflineEvents(grpc.ClientStreamingServer[SovereignFinancialEvent, BatchAckResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamOfflineEvents not implemented")
}
func (UnimplementedAccountingSwarmProtocolServer) StreamCRDTUpdates(grpc.ClientStreamingServer[CRDTStateBundle, BatchAckResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamCRDTUpdates not implemented")
}
func (UnimplementedAccountingSwarmProtocolServer) SwarmEventExchange(grpc.BidiStreamingServer[SovereignFinancialEvent, SovereignFinancialEvent]) error {
	return status.Error(codes.Unimplemented, "method SwarmEventExchange not implemented")
}
func (UnimplementedAccountingSwarmProtocolServer) SyncCRDTState(grpc.BidiStreamingServer[CRDTStateBundle, CRDTStateBundle]) error {
	return status.Error(codes.Unimplemented, "method SyncCRDTState not implemented")
}
func (UnimplementedAccountingSwarmProtocolServer) AgentCommunication(grpc.BidiStreamingServer[AgentMessage, AgentMessage]) error {
	return status.Error(codes.Unimplemented, "method AgentCommunication not implemented")
}
func (UnimplementedAccountingSwarmProtocolServer) mustEmbedUnimplementedAccountingSwarmProtocolServer() {
}
func (UnimplementedAccountingSwarmProtocolServer) testEmbeddedByValue() {}

// UnsafeAccountingSwarmProtocolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountingSwarmProtocolServer will
// result in compilation errors.
type UnsafeAccountingSwarmProtocolServer interface {
	mustEmbedUnimplementedAccountingSwarmProtocolServer()
}

func RegisterAccountingSwarmProtocolServer(s grpc.ServiceRegistrar, srv AccountingSwarmProtocolServer) {
	// If the following call panics, it indicates UnimplementedAccountingSwarmProtocolServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountingSwarmProtocol_ServiceDesc, srv)
}

func _AccountingSwarmProtocol_BroadcastFinancialEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SovereignFinancialEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingSwarmProtocolServer).BroadcastFinancialEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingSwarmProtocol_BroadcastFinancialEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingSwarmProtocolServer).BroadcastFinancialEvent(ctx, req.(*SovereignFinancialEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountingSwarmProtocol_GetEventById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingSwarmProtocolServer).GetEventById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingSwarmProtocol_GetEventById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingSwarmProtocolServer).GetEventById(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountingSwarmProtocol_GetEventsByRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingSwarmProtocolServer).GetEventsByRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingSwarmProtocol_GetEventsByRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingSwarmProtocolServer).GetEventsByRange(ctx, req.(*GetEventsRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountingSwarmProtocol_RequestReconciliation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconciliationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingSwarmProtocolServer).RequestReconciliation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingSwarmProtocol_RequestReconciliation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingSwarmProtocolServer).RequestReconciliation(ctx, req.(*ReconciliationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountingSwarmProtocol_ResolveLedgerConflict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConflictResolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingSwarmProtocolServer).ResolveLedgerConflict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingSwarmProtocol_ResolveLedgerConflict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingSwarmProtocolServer).ResolveLedgerConflict(ctx, req.(*ConflictResolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountingSwarmProtocol_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountingSwarmProtocolServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeRequest, SovereignFinancialEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_SubscribeEventsServer = grpc.ServerStreamingServer[SovereignFinancialEvent]

func _AccountingSwarmProtocol_StreamReconciliation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReconciliationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountingSwarmProtocolServer).StreamReconciliation(m, &grpc.GenericServerStream[ReconciliationRequest, ReconciliationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_StreamReconciliationServer = grpc.ServerStreamingServer[ReconciliationResponse]

func _AccountingSwarmProtocol_StreamOfflineEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AccountingSwarmProtocolServer).StreamOfflineEvents(&grpc.GenericServerStream[SovereignFinancialEvent, BatchAckResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_StreamOfflineEventsServer = grpc.ClientStreamingServer[SovereignFinancialEvent, BatchAckResponse]

func _AccountingSwarmProtocol_StreamCRDTUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AccountingSwarmProtocolServer).StreamCRDTUpdates(&grpc.GenericServerStream[CRDTStateBundle, BatchAckResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_StreamCRDTUpdatesServer = grpc.ClientStreamingServer[CRDTStateBundle, BatchAckResponse]

func _AccountingSwarmProtocol_SwarmEventExchange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AccountingSwarmProtocolServer).SwarmEventExchange(&grpc.GenericServerStream[SovereignFinancialEvent, SovereignFinancialEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_SwarmEventExchangeServer = grpc.BidiStreamingServer[SovereignFinancialEvent, SovereignFinancialEvent]

func _AccountingSwarmProtocol_SyncCRDTState_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AccountingSwarmProtocolServer).SyncCRDTState(&grpc.GenericServerStream[CRDTStateBundle, CRDTStateBundle]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_SyncCRDTStateServer = grpc.BidiStreamingServer[CRDTStateBundle, CRDTStateBundle]

func _AccountingSwarmProtocol_AgentCommunication_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AccountingSwarmProtocolServer).AgentCommunication(&grpc.GenericServerStream[AgentMessage, AgentMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountingSwarmProtocol_AgentCommunicationServer = grpc.BidiStreamingServer[AgentMessage, AgentMessage]

// AccountingSwarmProtocol_ServiceDesc is the grpc.ServiceDesc for AccountingSwarmProtocol service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountingSwarmProtocol_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cps.enterprise.v4.AccountingSwarmProtocol",
	HandlerType: (*AccountingSwarmProtocolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastFinancialEvent",
			Handler:    _AccountingSwarmProtocol_BroadcastFinancialEvent_Handler,
		},
		{
			MethodName: "GetEventById",
			Handler:    _AccountingSwarmProtocol_GetEventById_Handler,
		},
		{
			MethodName: "GetEventsByRange",
			Handler:    _AccountingSwarmProtocol_GetEventsByRange_Handler,
		},
		{
			MethodName: "RequestReconciliation",
			Handler:    _AccountingSwarmProtocol_RequestReconciliation_Handler,
		},
		{
			MethodName: "ResolveLedgerConflict",
			Handler:    _AccountingSwarmProtocol_ResolveLedgerConflict_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _AccountingSwarmProtocol_SubscribeEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamReconciliation",
			Handler:       _AccountingSwarmProtocol_StreamReconciliation_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOfflineEvents",
			Handler:       _AccountingSwarmProtocol_StreamOfflineEvents_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamCRDTUpdates",
			Handler:       _AccountingSwarmProtocol_StreamCRDTUpdates_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SwarmEventExchange",
			Handler:       _AccountingSwarmProtocol_SwarmEventExchange_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SyncCRDTState",
			Handler:       _AccountingSwarmProtocol_SyncCRDTState_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AgentCommunication",
			Handler:       _AccountingSwarmProtocol_AgentCommunication_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cps_enterprise_v4.proto",
}

const (
	QueryProtocol_GetBranchSummary_FullMethodName   = "/cps.enterprise.v4.QueryProtocol/GetBranchSummary"
	QueryProtocol_GetInventoryStatus_FullMethodName = "/cps.enterprise.v4.QueryProtocol/GetInventoryStatus"
	QueryProtocol_GetSalesReport_FullMethodName     = "/cps.enterprise.v4.QueryProtocol/GetSalesReport"
	QueryProtocol_GetLedgerBalance_FullMethodName   = "/cps.enterprise.v4.QueryProtocol/GetLedgerBalance"
	QueryProtocol_SubscribeDashboard_FullMethodName = "/cps.enterprise.v4.QueryProtocol/SubscribeDashboard"
)

// QueryProtocolClient is the client API for QueryProtocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryProtocolClient interface {
	// Read model queries
	GetBranchSummary(ctx context.Context, in *BranchQuery, opts ...grpc.CallOption) (*BranchSummary, error)
	GetInventoryStatus(ctx context.Context, in *InventoryQuery, opts ...grpc.CallOption) (*InventoryStatus, error)
	GetSalesReport(ctx context.Context, in *SalesReportQuery, opts ...grpc.CallOption) (*SalesReport, error)
	GetLedgerBalance(ctx context.Context, in *LedgerQuery, opts ...grpc.CallOption) (*LedgerBalance, error)
	// Real-time projections
	SubscribeDashboard(ctx context.Context, in *DashboardSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DashboardUpdate], error)
}

type queryProtocolClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryProtocolClient(cc grpc.ClientConnInterface) QueryProtocolClient {
	return &queryProtocolClient{cc}
}

func (c *queryProtocolClient) GetBranchSummary(ctx context.Context, in *BranchQuery, opts ...grpc.CallOption) (*BranchSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BranchSummary)
	err := c.cc.Invoke(ctx, QueryProtocol_GetBranchSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryProtocolClient) GetInventoryStatus(ctx context.Context, in *InventoryQuery, opts ...grpc.CallOption) (*InventoryStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InventoryStatus)
	err := c.cc.Invoke(ctx, QueryProtocol_GetInventoryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryProtocolClient) GetSalesReport(ctx context.Context, in *SalesReportQuery, opts ...grpc.CallOption) (*SalesReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SalesReport)
	err := c.cc.Invoke(ctx, QueryProtocol_GetSalesReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryProtocolClient) GetLedgerBalance(ctx context.Context, in *LedgerQuery, opts ...grpc.CallOption) (*LedgerBalance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedgerBalance)
	err := c.cc.Invoke(ctx, QueryProtocol_GetLedgerBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryProtocolClient) SubscribeDashboard(ctx context.Context, in *DashboardSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DashboardUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QueryProtocol_ServiceDesc.Streams[0], QueryProtocol_SubscribeDashboard_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DashboardSubscription, DashboardUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryProtocol_SubscribeDashboardClient = grpc.ServerStreamingClient[DashboardUpdate]

// QueryProtocolServer is the server API for QueryProtocol service.
// All implementations must embed UnimplementedQueryProtocolServer
// for forward compatibility.
type QueryProtocolServer interface {
	// Read model queries
	GetBranchSummary(context.Context, *BranchQuery) (*BranchSummary, error)
	GetInventoryStatus(context.Context, *InventoryQuery) (*InventoryStatus, error)
	GetSalesReport(context.Context, *SalesReportQuery) (*SalesReport, error)
	GetLedgerBalance(context.Context, *LedgerQuery) (*LedgerBalance, error)
	// Real-time projections
	SubscribeDashboard(*DashboardSubscription, grpc.ServerStreamingServer[DashboardUpdate]) error
	mustEmbedUnimplementedQueryProtocolServer()
}

// UnimplementedQueryProtocolServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryProtocolServer struct{}

func (UnimplementedQueryProtocolServer) GetBranchSummary(context.Context, *BranchQuery) (*BranchSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBranchSummary not implemented")
}
func (UnimplementedQueryProtocolServer) GetInventoryStatus(context.Context, *InventoryQuery) (*InventoryStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventoryStatus not implemented")
}
func (UnimplementedQueryProtocolServer) GetSalesReport(context.Context, *SalesReportQuery) (*SalesReport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSalesReport not implemented")
}
func (UnimplementedQueryProtocolServer) GetLedgerBalance(context.Context, *LedgerQuery) (*LedgerBalance, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedgerBalance not implemented")
}
func (UnimplementedQueryProtocolServer) SubscribeDashboard(*DashboardSubscription, grpc.ServerStreamingServer[DashboardUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribeDashboard not implemented")
}
func (UnimplementedQueryProtocolServer) mustEmbedUnimplementedQueryProtocolServer() {}
func (UnimplementedQueryProtocolServer) testEmbeddedByValue()                       {}

// UnsafeQueryProtocolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryProtocolServer will
// result in compilation errors.
type UnsafeQueryProtocolServer interface {
	mustEmbedUnimplementedQueryProtocolServer()
}

func RegisterQueryProtocolServer(s grpc.ServiceRegistrar, srv QueryProtocolServer) {
	// If the following call panics, it indicates UnimplementedQueryProtocolServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueryProtocol_ServiceDesc, srv)
}

func _QueryProtocol_GetBranchSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BranchQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryProtocolServer).GetBranchSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryProtocol_GetBranchSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryProtocolServer).GetBranchSummary(ctx, req.(*BranchQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryProtocol_GetInventoryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryProtocolServer).GetInventoryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryProtocol_GetInventoryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryProtocolServer).GetInventoryStatus(ctx, req.(*InventoryQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryProtocol_GetSalesReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalesReportQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryProtocolServer).GetSalesReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryProtocol_GetSalesReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryProtocolServer).GetSalesReport(ctx, req.(*SalesReportQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryProtocol_GetLedgerBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedgerQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryProtocolServer).GetLedgerBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryProtocol_GetLedgerBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryProtocolServer).GetLedgerBalance(ctx, req.(*LedgerQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryProtocol_SubscribeDashboard_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DashboardSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryProtocolServer).SubscribeDashboard(m, &grpc.GenericServerStream[DashboardSubscription, DashboardUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryProtocol_SubscribeDashboardServer = grpc.ServerStreamingServer[DashboardUpdate]

// QueryProtocol_ServiceDesc is the grpc.ServiceDesc for QueryProtocol service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryProtocol_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cps.enterprise.v4.QueryProtocol",
	HandlerType: (*QueryProtocolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBranchSummary",
			Handler:    _QueryProtocol_GetBranchSummary_Handler,
		},
		{
			MethodName: "GetInventoryStatus",
			Handler:    _QueryProtocol_GetInventoryStatus_Handler,
		},
		{
			MethodName: "GetSalesReport",
			Handler:    _QueryProtocol_GetSalesReport_Handler,
		},
		{
			MethodName: "GetLedgerBalance",
			Handler:    _QueryProtocol_GetLedgerBalance_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeDashboard",
			Handler:       _QueryProtocol_SubscribeDashboard_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cps_enterprise_v4.proto",
}
